name: Daily SSH Key Login

on:
  schedule:
    # 每天凌晨 1 点运行
    - cron: '0 1 * * *'

jobs:
  ssh-login:
    runs-on: debian-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ matrix.server.ip }}" >> ~/.ssh/known_hosts

      - name: SSH Login and Execute Commands
        run: |
          ssh "${{ matrix.server.user }}@${{ matrix.server.ip }}" <<EOF
          echo "SSH 登录成功！这是每日任务执行。"
          # 在这里可以添加更多命令
          EOF
