name: Daily SSH Key Login

on:
  schedule:
    # 每天凌晨 1 点运行
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: S1
        uses: actions/checkout@v3


