name: Daily SSH Key Login

on:
  schedule:
    # 每天凌晨 1 点运行
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.S12 }}
        username: ${{ secrets.USER1 }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: whoami


