name: test

on:
  workflow_dispatch:

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: test1
      run: |
        chmod +x test.sh
        bash test.sh
    
        
    
