name: test

on:
  workflow_dispatch:

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: test1
      run: |
        chmod +x test.sh
        bash test.sh > output.log 2>&1

    - name: Commit and push results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output.log
        git commit -m "Add output.log from workflow"
        git push
    
        
    
