name: test

on:
  workflow_dispatch:

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: test1
      run: |
        chmod +x 1.sh
        bash ./1.sh
    
        
    
