name: upgrade_xray

on:
  workflow_dispatch:

jobs:

  upgrade_xray:
    name: upgrade_xray
    runs-on: ubuntu-latest
    steps:
    - name: user1
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.S12 }}
        username: ${{ secrets.USER1 }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: bash -c 'wget -qO- https://raw.githubusercontent.com/good-xuan/serv00/refs/heads/main/01.xray.sh | bash&&pkill ws'  
    - name: user2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.S13 }}
        username: ${{ secrets.USER2 }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: bash -c 'wget -qO- https://raw.githubusercontent.com/good-xuan/serv00/refs/heads/main/01.xray.sh | bash&&pkill ws'  
    - name: user3
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.S13 }}
        username: ${{ secrets.USER3 }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: bash -c 'wget -qO- https://raw.githubusercontent.com/good-xuan/serv00/refs/heads/main/01.xray.sh | bash&&pkill ws'  
    - name: user4
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.S13 }}
        username: ${{ secrets.USER4 }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: bash -c 'wget -qO- https://raw.githubusercontent.com/good-xuan/serv00/refs/heads/main/01.xray.sh | bash&&pkill ws'  

